![图片1](灰色关联分析_01.png)

In [1]:
import numpy as np

A = np.array([[55,24,10],[65,38,22],[75,40,18],[100,50,20]])

![图片1](灰色关联分析_04.png)

In [2]:
#求出每列均值用于预处理
Mean = np.mean(A,axis=0)

#预处理后矩阵
A_norm = A / Mean

print("预处理后矩阵为：\n",A_norm)

预处理后矩阵为：
 [[0.74576271 0.63157895 0.57142857]
 [0.88135593 1.         1.25714286]
 [1.01694915 1.05263158 1.02857143]
 [1.3559322  1.31578947 1.14285714]]


![图片2](灰色关联分析_02.png)

In [3]:
#母序列
Y = A_norm[:,0]

![图片3](灰色关联分析_03.png)

In [4]:
#子序列
X = A_norm[:,1:]

![图片4](灰色关联分析_05.png)

In [5]:
# 计算|X0 - Xi|矩阵（X0为母序列Y)
absX0_Xi = np.abs(X - np.tile(Y.reshape(-1, 1), (1, X.shape[1])))

# 计算两级最小差a
a = np.min(absX0_Xi)

# 计算量级最大差b
b = np.max(absX0_Xi)

# 分辨系数取0.5
rho = 0.5

![图片5](灰色关联分析_06.png)

In [6]:
gamma = (a + rho * b) / (absX0_Xi + rho * b)

print("子序列中各个指标的灰色关联度分别为：")
print(np.mean(gamma, axis=0))

子序列中各个指标的灰色关联度分别为：
[0.76966578 0.60058464]
